apiVersion: v1
kind: Pod
metadata:
  name: template-jenkins-pipeline
  labels:
    purpose: cicd-jenkins-agent
    spotinst.io/restrict-scale-down: "true"
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
spec:
  serviceAccountName: jenkins-service-account
  imagePullSecrets:
    - name: jfrog-dockerconfigjson
  containers:
    - name: jnlp
      image: tealium-docker-virtual-registry.jfrog.io/jenkins/inbound-agent:4.13.3-1
      # jnlp image entrypoint does what we want so we do not specify a command
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      env:
        - name: ACCOUNT_ID
          valueFrom:
            configMapKeyRef:
              name: environment-metadata
              key: accountID
        - name: ACCOUNT_NAME
          valueFrom:
            configMapKeyRef:
              name: environment-metadata
              key: accountName
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: environment-metadata
              key: environmentName
        - name: ENVIRONMENT_PREFIX
          valueFrom:
            configMapKeyRef:
              name: environment-metadata
              key: environmentPrefix
        - name: ENVIRONMENT_TYPE
          valueFrom:
            configMapKeyRef:
              name: environment-metadata
              key: environmentType
        - name: PLATFORM_NAME
          valueFrom:
            configMapKeyRef:
              name: environment-metadata
              key: platformName
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: environment-metadata
              key: region
    - name: webhooks
      image: tealium-docker-virtual-registry.jfrog.io/jenkins-webhooks-container:latest
      command: [tail, -f, /dev/null]
      resources:
        requests:
          memory: 256Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 1000m
  volumes:
    - emptyDir: {}
      name: tealium-dependencies
